Add support for MBF21 weapon flags
MTrop/DoomTools pull request #19
Opened 2021-05-02 22:35 UTC by XaserAcheron

Adds support for MBF21's new weapon flags field -- works just the same as thing flags: +FLAGNAME to set, -FLAGNAME to unset.

The DEHWeaponFlag implementation is more complex than I'd have liked, but  I needed to iterate through the list a couple of times so a bunch of `static final const`s wouldn't cut it. Lemme know if you've got any ideas on how to slim this down a bit (or if it's OK as-is) -- my Java-Fu is weak. :P

2021-05-06 19:13 UTC, MTrop requested changes
Good stuff. Just one required change plus an optional one that would take a little more time to change. Up to you, Xaser.

2021-05-06 19:13 UTC, MTrop commented on src/main/java/net/mtrop/doom/tools/decohack/DecoHackParser.java
> +		}
There's definitely an improvement that can be done here by making a static name lookup map in `DEHWeaponFlag` but I'm fine with kicking that can down the road when I dig back into the parser, later.

2021-05-06 19:13 UTC, MTrop commented on src/main/java/net/mtrop/doom/tools/decohack/data/DEHWeapon.java
> +		}
In light of the counter-proposed changes to the field spec, this should be changed to write just the integer value a la `DEHThing`.

2021-05-08 20:03 UTC, XaserAcheron commented
Simplified the export so it just writes the number now; works great in latest dsda-doom `master`, so all is well now. :)

I'll hold off on the other suggested change if you don't mind, 'cause I gotta shift my focus back to the port itself. I'm already juggling too many to-dos already. :P

2021-05-09 03:40 UTC, MTrop approved these changes
Cool. Merging it in.

2021-05-09 03:40 UTC, merged